### PR TITLE
Feature/handle 404s

### PR DESCRIPTION
**Pull request by Thoompa**
Added a page to capture any routes which aren't accounted for. It's very simple so happy to redo it once we have a wireframe from Rob (if we think that's worth the effort)

image

### CODE REVIEW

**Comment by halbrd** [comment]
Thanks for the PR @Thoompa / @TimHarris96 !

Linguistically, some cleanup:

> Oops!
> This page does not exist. Click here to return to Project QWERTY.

The markup/styling can be compressed. I suggest minimal layout using HTML5 canonical elements:

```html
<main>
  <h1>Oops!</h1>
  <p>This page does not exist. <a class="link" v-on:click="$router.push('/')">Click here</a> to return to Project QWERTY.</p>
</main>
```

```css
main {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
```

As for styling the link, I don't know why it doesn't have normal link styling (blue + pointer) automatically. I'll look into that and get back to you on this PR. Could be that there's a problem that needs a separate fix to master.

**Comment by halbrd** [comment]
Figured out the link styling. Still not sure why `<a>` doesn't style, but for the `router` system we're using the right way to link seems to be `<router-link to="/" >Home</router-link>` (see https://stackoverflow.com/a/61781008).

So replace 
```
<a v-on:click="$router.push('/')">Click here</a>
```
with
```
<router-link to="/" >Click here</router-link>
```
and delete the `.link` styling.

@Thoompa / @TimHarris96

**Comment by Thoompa** [comment]
> 

This works except that the 

> Oops!

is no longer centred. I tried adding `h1 {
  display: flex;
  justify-content: center;}` but that didn't work. I tried removing each line of CSS and they're all necessary. We were able to change the `<div class='column' ` to `<main` though so I agree that is better

**Comment by halbrd** [comment]
Riiight, the `h1` and `p` elements are `display: block` elements so they take up the full width. Centering the element itself has no effect because there's no margin on either side to begin with. 

They're aligned to the left because that's the default for text. We just need to give them `text-align: center`. 

Since the flex isn't needed to center it now, we can get rid of it completely.

image

image

Doesn't get simpler than that :smiley:

**Comment by Thoompa** [comment]
> 

Excellent, pushed!

**Comment by halbrd** [comment]
Nice!

Now you need to fix the indentation 😎

**Comment by Thoompa** [comment]
Whoops forgot to reformat, think it's good now

**Review by halbrd — APPROVED** [review]
Fantastic, thanks so much for building this feature! Welcome back to Project QWERTY :)

I'll leave you the honours of merging your work!

**Pull request merged**
